name: travel_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  icon_decoration: ^2.0.2
  bloc:
  flutter_bloc:
  equatable:
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/imgs/welcome1.jpeg
    - assets/imgs/welcome2.jpeg
    - assets/imgs/welcome3.jpeg
    - assets/imgs/arrow_right_icon.png
    - assets/imgs/mountain.jpeg
    - assets/imgs/skateboarding.png
    - assets/imgs/biking.png
    - assets/imgs/bg.jpg


